### ISSUE TITLE
Discussion: Should we create identification scheme for action tracking?

### ISSUE THREAD

**Issue by toomb1r** [toomb1r/TeamProjects2_Team6#8]
Hey, we could have an ID number in our pull requests that links back to some schedule or milestone sheet to track which ones are complete or not. Thoughts?

![image](https://github.com/toomb1r/TeamProjects2_Team6/assets/97482507/37d92415-b15a-409d-a778-3d3e2063548f)

**Comment by ReginPotter** [comment]
We could bring this up as a group tomorrow but I would like some more information about it
